name: Update prices

on:
  workflow_dispatch:

  # Run once a day at 21:00 UTC / 06:00 JST / 17:00 EDT
  # Yuyu-tei updates usually land before 13:00 UTC.
  # TCGplayer content updates usually land around 20:00 UTC.
  schedule:
    - cron: '0 21 * * *'

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  update-prices:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1

      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Fetch existing assets
        run: |
          git fetch --depth=1 https://github.com/Qrimpuff/hocg-fan-sim-assets gh-pages:assets-gh-pages --force
          git worktree add --detach assets assets-gh-pages

      - name: Fetch existing prices
        run: |
          git fetch --depth=1 origin gh-pages:prices-gh-pages --force
          git worktree add --detach prices prices-gh-pages

      - name: Run
        env:
          SCRAPERAPI_API_KEY: ${{ secrets.SCRAPERAPI_API_KEY }}
        run: cargo run --release -- --yuyutei --tcgplayer

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: prices
          clean: true
          commit-message: Update prices